name: Ruby Test

on:
  workflow_call:
    secrets:
      BUNDLE_RUBYGEMS__PKG__GITHUB__COM:
        description: "The GitHub token to use for private gem sources"
        required: true
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      BUNDLE_RUBYGEMS__PKG__GITHUB__COM: ${{ secrets.BUNDLE_RUBYGEMS__PKG__GITHUB__COM }}
    services:
      redis:
        image: redis
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379
    steps:
      - uses: actions/checkout@v7
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - run: bundle exec rspec
